"""add_verb_conjugations_table

Revision ID: edf0e7a66587
Revises: 841f45df2c2a
Create Date: 2026-03-07 18:15:34.333261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf0e7a66587'
down_revision: Union[str, Sequence[str], None] = '841f45df2c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verb_conjugations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('infinitive', sa.String(), nullable=False),
    sa.Column('english_translation', sa.String(), nullable=True),
    sa.Column('verb_type', sa.String(), nullable=True),
    sa.Column('conjugation_data', sa.Text(), nullable=False),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verb_conjugations_id'), 'verb_conjugations', ['id'], unique=False)
    op.create_index(op.f('ix_verb_conjugations_infinitive'), 'verb_conjugations', ['infinitive'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verb_conjugations_infinitive'), table_name='verb_conjugations')
    op.drop_index(op.f('ix_verb_conjugations_id'), table_name='verb_conjugations')
    op.drop_table('verb_conjugations')
    # ### end Alembic commands ###
